name: Maven Publish

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Setup GPG
        run: |
          mkdir -p ~/.gnupg
          chmod 700 ~/.gnupg
          sudo su
          echo "pinentry-mode loopback" >> ~/.gnupg/gpg.conf
          echo "allow-loopback-pinentry" >> ~/.gnupg/gpg-agent.conf
          gpgconf --kill all
          echo "${{ secrets.GPG_PRIVATE_KEY }}" > private.key
          sed -i 's/\\n/\n/g' private.key
          gpg --batch --import private.key
          rm private.key
          echo -e "trust\n5\ny\nsave\n" | gpg --command-fd 0 --edit-key "${{ secrets.GPG_KEY_ID }}"
          gpg --list-secret-keys --keyid-format LONG

      - name: Build and Deploy
        run: |
          mvn -B clean deploy -DskipTests \
            -P release-sign-artifacts \
            -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }} \
            -Dgpg.homedir=$HOME/.gnupg \
            --settings settings.xml
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          GPG_TTY: /dev/console

      - name: Verify Signatures
        run: |
          find target -name '*.asc' -exec gpg --verify {} \;
